### ISSUE TITLE
Error al obtener datos desde la API

### ISSUE THREAD

**Issue by leoguga** [UCA-Datalab/covid_occupancy_simulation#12]
La función generate_plot_data de web.backend muestra el siguiente error si se ejecuta con los parámetros 'cadiz' y 'admitted':

Traceback (most recent call last):
  File "/home/leopoldo/gitroot/covid19-api/venv_covid19-api/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2646, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc  File "pandas/_libs/hashtable_class_helper.pxi", line 1619, in pandas._libs.hashtable.PyObjectHashTable.get_item  File "pandas/_libs/hashtable_class_helper.pxi", line 1627, in pandas._libs.hashtable.PyObjectHashTable.get_itemKeyError: 'admitted'During handling of the above exception, another exception occurred:Traceback (most recent call last):
  File "/home/leopoldo/gitroot/covid19-api/venv_covid19-api/lib/python3.6/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/leopoldo/gitroot/covid19-api/venv_covid19-api/lib/python3.6/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/leopoldo/gitroot/covid19-api/venv_covid19-api/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/leopoldo/gitroot/covid19-api/venv_covid19-api/lib/python3.6/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/leopoldo/gitroot/covid19-api/venv_covid19-api/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/leopoldo/gitroot/covid19-api/venv_covid19-api/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/leopoldo/gitroot/covid19-api/venv_covid19-api/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/leopoldo/gitroot/covid19-api/venv_covid19-api/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/leopoldo/gitroot/covid19-api/venv_covid19-api/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/leopoldo/gitroot/covid19-api/venv_covid19-api/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/leopoldo/gitroot/covid19-api/venv_covid19-api/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/leopoldo/gitroot/covid19-api/venv_covid19-api/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/leopoldo/gitroot/covid19-api/venv_covid19-api/lib/python3.6/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/home/leopoldo/gitroot/covid19-api/src/api.py", line 29, in plot
    dic_plot = generate_plot_data(path_data_folder, str(escape(region)), str(escape(chart)))
  File "/home/leopoldo/gitroot/covid19-api/src/web/backend.py", line 81, in generate_plot_data
    dic_plot = _plot_basic(df, plot_type)
  File "/home/leopoldo/gitroot/covid19-api/src/web/backend.py", line 36, in _plot_basic
    data = df[plot_type]
  File "/home/leopoldo/gitroot/covid19-api/venv_covid19-api/lib/python3.6/site-packages/pandas/core/frame.py", line 2799, in __getitem__
    return self._getitem_multilevel(key)
  File "/home/leopoldo/gitroot/covid19-api/venv_covid19-api/lib/python3.6/site-packages/pandas/core/frame.py", line 2849, in _getitem_multilevel
    loc = self.columns.get_loc(key)
  File "/home/leopoldo/gitroot/covid19-api/venv_covid19-api/lib/python3.6/site-packages/pandas/core/indexes/multi.py", line 2662, in get_loc
    loc = self._get_level_indexer(key, level=0)
  File "/home/leopoldo/gitroot/covid19-api/venv_covid19-api/lib/python3.6/site-packages/pandas/core/indexes/multi.py", line 2929, in _get_level_indexer
    code = self._get_loc_single_level_index(level_index, key)
  File "/home/leopoldo/gitroot/covid19-api/venv_covid19-api/lib/python3.6/site-packages/pandas/core/indexes/multi.py", line 2598, in _get_loc_single_level_index
    return level_index.get_loc(key)
  File "/home/leopoldo/gitroot/covid19-api/venv_covid19-api/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2648, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc  File "pandas/_libs/hashtable_class_helper.pxi", line 1619, in pandas._libs.hashtable.PyObjectHashTable.get_item  File "pandas/_libs/hashtable_class_helper.pxi", line 1627, in pandas._libs.hashtable.PyObjectHashTable.get_itemKeyError: 'admitted'

**Comment by daniprec** [comment]
"admitted" no es un parámetro válido para `plot_type`

Por propuesta de @davidggphy ahora la función arrojará un error y listará los `plot_type` válidos en caso de recibir uno incorrecto.
